[package]
name = "aiba"
version = "0.1.0"
authors = ["dbusteed <busteed.davis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
dirs = "3.0.1"
term = "0.7.0"
